#!/bin/bash

# Get the connected monitors
SCREENS=$(xrandr --query | grep ' connected' | wc -l)
if [ $SCREENS -eq 1 ]
then
  xrandr --output eDP1 --primary --mode 1366x768 --pos 0x0 
  xrandr --output HDMI1 --off
fi
 
if [ $SCREENS -eq 2 ]
then
  xrandr --output eDP1 --mode 1366x768 --pos 1366x0 --rotate normal --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --right-of eDP1 --output DP1 --off
fi
