#!/bin/bash

# Get the connected monitors
SCREENS=$(xrandr --query | grep ' connected' | wc -l)
if [ $SCREENS -eq 1 ]
then
  xrandr --output eDP-1 --mode 1366x768 --pos 0x0 
fi
 
if [ $SCREENS -eq 2 ]
then
  xrandr --output eDP-1 --mode 1366x768 --pos 1366x0 --rotate normal --output HDMI-1 --primary --mode 1366x768 --pos 0x0 --rotate normal --left-of eDP-1 --output DP-1 --off
fi
