#!/bin/bash

# Get the connected monitors
SCREENS=$(xrandr --query | grep ' connected' | wc -l)
if [ $SCREENS -eq 1 ]
then
  xrandr --output eDP1 --primary --mode 1366x768 --pos 0x0 
  xrandr --output HDMI1 --off
fi
 
if [ $SCREENS -eq 2 ]
then
#  xrandr --output HDMI1 --mode 1920x1080 --scale 1x1 --output eDP1 --mode 1366x768 --scale 1x1 --same-as HDMI1
  xrandr --output eDP1 --mode 1366x768 --scale 1x1 --output HDMI1 --mode 1920x1080 --scale 1x1 --same-as eDP1
fi
