
[env]
TERM = "xterm-256color"

[font.normal]
family = "Fira Code"
style = "Retina"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "L"
mods = "Control|Shift"

[terminal.shell]
program = "/bin/zsh"

[window]
startup_mode = "Maximized"

[window.dimensions]
columns = 133
lines = 40

[general]
import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]
